sudo: required
services:
  - docker

before_install:
  - docker build -t yaqoobch/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yaqoobch/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-609088430567"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
      secure: "$AWS_SECRET_KEY"
